# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=vivek

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway (important)
spring.flyway.enabled=true

# Optional logging
//spring.jpa.show-sql=true
logging.level.org.springframework=ERROR
logging.level.com.example=INFO